services:                                                                        
    - type: web                                                                    
      name: twikoo                                                                 
      runtime: node                                                                
      plan: free                                                                   
      buildCommand: npm install                                                    
      startCommand: npx tkserver                                                   
      envVars:                                                                     
        - key: MONGODB_URL                                                         
          sync: false                                                              
        - key: TWIKOO_IP_ENABLED                                                   
          value: "true"
